# Generated by Django 3.1.5 on 2021-01-14 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_educonsultantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educonsultantprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'Edu-Consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='profile_educonsultant', to=settings.AUTH_USER_MODEL),
        ),
    ]
