# Generated by Django 3.1.5 on 2021-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('profiles', '0003_auto_20210114_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='mentor_courses',
            field=models.ManyToManyField(blank=True, to='courses.ClassCourse'),
        ),
    ]
