# Generated by Django 3.1.5 on 2021-01-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_mentorprofile_mentor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='mentor_courses',
        ),
    ]
