# Generated by Django 3.1.5 on 2021-01-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_mentorprofile_mentor_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='my_mentor',
            field=models.ManyToManyField(blank=True, related_name='mentee_mentor', to='profiles.MentorProfile'),
        ),
    ]
