# Generated by Django 3.1.5 on 2021-02-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_menteeprofile_my_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeprofile',
            name='my_mentor',
        ),
    ]
