# Generated by Django 3.1.5 on 2021-01-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('educonsultant', 'educonsultant')], default='Mentee', max_length=20),
        ),
    ]
