# Generated by Django 3.1.5 on 2021-01-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('educonsultant', 'Edu-Consultant')], max_length=20, null=True),
        ),
    ]
