# Generated by Django 3.1.5 on 2021-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210114_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('educonsultant', 'educonsultant')], default='Mentor', max_length=20),
        ),
    ]
