# Generated by Django 3.1.5 on 2021-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210114_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('Edu-Consultant', 'Edu-Consultant')], default='Mentee', max_length=20),
        ),
    ]
