# Generated by Django 3.1.5 on 2021-01-14 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCourseLectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('counselor', models.ManyToManyField(limit_choices_to={'role': 'Mentee'}, related_name='classcourse_educonsultant', to=settings.AUTH_USER_MODEL)),
                ('lectures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classcourse_lectures', to='courses.classcourselectures')),
                ('student', models.ManyToManyField(limit_choices_to={'role': 'Mentee'}, related_name='classcourse_mentee', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ManyToManyField(limit_choices_to={'role': 'Mentor'}, related_name='classcourse_mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
