# Generated by Django 3.1.5 on 2021-03-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCourseLectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('lectures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classcourse_lectures', to='courses.classcourse')),
            ],
        ),
        migrations.CreateModel(
            name='LecturesFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lecture_video_files')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='lecture_document_files')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('files_lectures', models.ManyToManyField(related_name='files_of_ClassCourseLectures', to='courses.ClassCourseLectures')),
            ],
        ),
    ]
