# Generated by Django 3.1.5 on 2021-01-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcourse',
            name='counselor',
        ),
        migrations.RemoveField(
            model_name='classcourse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classcourse',
            name='teacher',
        ),
    ]
