# Generated by Django 3.1.5 on 2021-01-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210114_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcourse',
            name='lectures',
        ),
        migrations.AddField(
            model_name='classcourselectures',
            name='lectures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classcourse_lectures', to='courses.classcourse'),
        ),
    ]
