# Generated by Django 3.1.5 on 2021-01-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_mentorprofile_mentor_courses'),
        ('courses', '0004_classcourse_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcourse',
            name='teacher',
            field=models.ManyToManyField(related_name='classcourse_mentor', to='profiles.MentorProfile'),
        ),
    ]
