# Generated by Django 3.1.5 on 2021-01-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_menteeprofile_my_mentor'),
        ('courses', '0005_auto_20210115_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcourse',
            name='consultant',
            field=models.ManyToManyField(related_name='classcourse_educonsultant', to='profiles.EduconsultantProfile'),
        ),
        migrations.AddField(
            model_name='classcourse',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classcourse',
            name='student',
            field=models.ManyToManyField(related_name='classcourse_mentee', to='profiles.MenteeProfile'),
        ),
        migrations.AddField(
            model_name='classcourselectures',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
