# Generated by Django 3.1.5 on 2021-01-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210115_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturesFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video_files')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='document_files')),
                ('files_lectures', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files_lectures_of_ClassCourseLectures', to='courses.classcourselectures')),
            ],
        ),
    ]
