# Generated by Django 3.1.5 on 2021-01-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210117_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturesfiles',
            name='files_lectures',
        ),
        migrations.AddField(
            model_name='lecturesfiles',
            name='files_lectures',
            field=models.ManyToManyField(related_name='files_of_ClassCourseLectures', to='courses.ClassCourseLectures'),
        ),
    ]
