# Generated by Django 3.1.5 on 2021-01-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210117_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesfiles',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
