# Generated by Django 3.1.5 on 2021-01-17 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_menteeprofile_my_mentor'),
        ('courses', '0010_lecturesfiles_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcourse',
            name='course_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_creator', to='profiles.mentorprofile'),
        ),
    ]
