# Generated by Django 3.1.5 on 2021-01-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_menteeprofile_my_mentor'),
        ('courses', '0011_classcourse_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcourse',
            name='course_creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_creator', to='profiles.mentorprofile'),
        ),
    ]
