# Generated by Django 3.1.5 on 2021-01-17 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0014_auto_20210117_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcourse',
            name='course_creator',
        ),
        migrations.AddField(
            model_name='classcourse',
            name='course_creator',
            field=models.ManyToManyField(default=None, related_name='course_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
