# Generated by Django 3.1.5 on 2021-01-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_auto_20210117_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcourse',
            name='course_creator',
        ),
        migrations.AddField(
            model_name='classcourse',
            name='course_creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
